[repository]
name = "hyprland-plugins"
authors = ["Vaxry"]
commit_pins = [
    ["3bb9c7c5cf4f2ee30bf821501499f2308d616f94", "efee74a7404495dbda70205824d6e9fc923ccdae"],
    ["d74607e414dcd16911089a6d4b6aeb661c880923", "efee74a7404495dbda70205824d6e9fc923ccdae"],
    ["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "f7853b9cc6aab627b37b7be6575628e788ad6d1d"],
    ["84ab8d11e8951a6551d1e1bf87796a8589da6d47", "8af29f09c5b132d5087c2931fe9bd34f63923ba1"],
    ["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "f99822818ec8276cfd6ec99ab60c4708c9884e3d"],
    ["c5e28ebcfe00a510922779b2c568cfa52a317445", "4c9d83b981ad4668b89b8a3dc24d6f3ea7ad08fd"], # 0.37.0
    ["19c90048d65a5660384d2fb865926a366696d6be", "4c9d83b981ad4668b89b8a3dc24d6f3ea7ad08fd"], # 0.37.1
    ["3875679755014997776e091ff8903acfb311dd2f", "e45066d0741a1a4b9298a4c5ec43a5e57b059a4e"]  # 0.38.0
]

[borders-plus-plus]
description = "A plugin to add more borders to windows."
authors = ["Vaxry"]
output = "borders-plus-plus/borders-plus-plus.so"
build = [
    "make -C borders-plus-plus all",
]

[csgo-vulkan-fix]
description = "A plugin to fix incorrect mouse offsets on csgo in Vulkan"
authors = ["Vaxry"]
output = "csgo-vulkan-fix/csgo-vulkan-fix.so"
build = [
    "make -C csgo-vulkan-fix all",
]

[hyprbars]
description = "A plugin to add title bars to windows"
authors = ["Vaxry"]
output = "hyprbars/hyprbars.so"
build = [
    "make -C hyprbars all",
]

[hyprtrails]
description = "A plugin to add trails behind moving windows"
authors = ["Vaxry"]
output = "hyprtrails/hyprtrails.so"
build = [
    "make -C hyprtrails all",
]

[hyprwinwrap]
description = "A clone of xwinwrap for Hyprland"
authors = ["Vaxry"]
output = "hyprwinwrap/hyprwinwrap.so"
build = [
    "make -C hyprwinwrap all",
]

[hyprexpo]
description = "Overview plugin like gnome kde or wf"
authors = ["Vaxry"]
output = "hyprexpo/hyprexpo.so"
build = [
    "make -C hyprexpo all"
]

